# Generated by Django 4.1.4 on 2022-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("user", models.CharField(max_length=50, verbose_name="사용자 이름")),
                ("content", models.TextField(verbose_name="내용")),
                ("region", models.CharField(max_length=50, verbose_name="지역")),
                ("price", models.IntegerField(verbose_name="가격")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "게시글",
                "db_table": "post",
            },
        ),
    ]
